name: 📚 Documentation Issue
description: Report problems with documentation, examples, or guides
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 
        Clear and accurate documentation is crucial for a great developer experience.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README.md
        - OpenAPI specification
        - Code examples
        - Contributing guide
        - API response examples
        - Use case documentation
        - Installation/setup guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue?
      options:
        - Typo/grammar error
        - Unclear explanation
        - Missing information
        - Incorrect information
        - Broken link
        - Outdated content
        - Missing example
        - Confusing example
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue?
      placeholder: |
        File: README.md
        Section: Email Validation
        Line: 125
        Or provide a URL if applicable
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say?
      placeholder: Copy the problematic text here
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should it be fixed or improved?
      placeholder: Provide the corrected text or describe the improvement
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Why is this confusing? How did you encounter this issue? Screenshots? 