name: ✨ Feature Request
description: Suggest improvements to the OpenAPI specification or documentation
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting improvements to the LeadMagic OpenAPI specification!
        Your ideas help make this resource better for all developers.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of improvement are you suggesting?
      options:
        - New endpoint documentation
        - Better examples
        - Additional use cases
        - Developer tools/utilities
        - Documentation improvements
        - Code generation improvements
        - Testing enhancements
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: Provide a concrete example of how this would be beneficial

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my work
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Links to relevant documentation, examples from other APIs, etc. 